project:
  type: book
  output-dir: docs

book:
  title: "book2"
  author: "Norah Jones"
  date: "05/12/2024"
  
  page-footer: 
    left: "Made with [FRB-CESAB](https://www.fondationbiodiversite.fr/en/about-the-foundation/le-cesab/)"
    center: "Code source available on [{{< fa brands github >}}](https://github.com/VDjianBiogeo/projet_pastis/tree/dev)"
    right: "Built with [Quarto](https://quarto.org/)"
    border: true
    
  chapters:
    - index.qmd
    - meteo_summary.qmd
    - survey_summary.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

